contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #salmonidx channel"
    url: https://nfcore.slack.com/channels/salmonidx
    about: Discussion about the nf-core/salmonidx pipeline
